services:
  db:
    image: postgres:16
    container_name: tasklist-postgres
    environment:
      POSTGRES_DB: tasklist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasklist"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: tasklist-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tasklist
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

volumes:
  db_data:
